name        : at-spi2-atk
version     : 2.18.1
release     : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/at-spi2-atk/2.18/at-spi2-atk-2.18.1.tar.xz : c4b15f9386d34d464ddad5f6cc85669742c016df87141ceee93513245979c12d
license     :
    - GPL-3.0
summary     : Accessibility toolkit - ATK D-Bus Bridge
builddeps   :
    - pkgconfig(atk)
    - pkgconfig(atspi-2)
description : |
    The At-Spi2 Atk package contains a library that bridges ATK to At-Spi2 D-Bus service.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
