name       : at-spi2-atk
version    : 2.20.1
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/at-spi2-atk/2.20/at-spi2-atk-2.20.1.tar.xz : 2358a794e918e8f47ce0c7370eee8fc8a6207ff1afe976ec9ff547a03277bf8e
license    :
    - GPL-3.0
summary    : Accessibility toolkit - ATK D-Bus Bridge
builddeps  :
    - pkgconfig(atk)
    - pkgconfig32(atk)
    - pkgconfig(atspi-2)
    - pkgconfig32(atspi-2)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The At-Spi2 Atk package contains a library that bridges ATK to At-Spi2 D-Bus service.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -rf $installdir/%libdir%/gnome-settings-daemon-3.0/
    fi
