name       : at-spi2-atk
version    : 2.34.0
release    : 19
source     :
    - https://download.gnome.org/sources/at-spi2-atk/2.34/at-spi2-atk-2.34.0.tar.xz : 3a9a7e96a1eb549529e60a42201dd78ccce413d9c1706e16351cc5288e064500
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : Accessibility toolkit - ATK D-Bus Bridge
description: |
    The At-Spi2 Atk package contains a library that bridges ATK to At-Spi2 D-Bus service.
builddeps  :
    - pkgconfig32(atk)
    - pkgconfig32(atspi-2)
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(libxml-2.0)
    - libgcrypt-32bit-devel
emul32     : yes
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -rf $installdir/%libdir%/gnome-settings-daemon-3.0/
    fi
