name       : at-spi2-atk
version    : 2.26.0
release    : 12
source     :
    - https://download.gnome.org/sources/at-spi2-atk/2.26/at-spi2-atk-2.26.0.tar.xz : d25e528e1406a10c7d9b675aa15e638bcbf0a122ca3681f655a30cce83272fb9
license    :
    - GPL-3.0
component  : desktop.gtk
summary    : Accessibility toolkit - ATK D-Bus Bridge
builddeps  :
    - pkgconfig(atk)
    - pkgconfig32(atk)
    - pkgconfig(atspi-2)
    - pkgconfig32(atspi-2)
    - pkgconfig(dbus-1)
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
emul32     : yes
description: |
    The At-Spi2 Atk package contains a library that bridges ATK to At-Spi2 D-Bus service.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -rf $installdir/%libdir%/gnome-settings-daemon-3.0/
    fi
