name       : at-spi2-atk
version    : 2.34.2
release    : 21
source     :
    - https://download.gnome.org/sources/at-spi2-atk/2.34/at-spi2-atk-2.34.2.tar.xz : 901323cee0eef05c01ec4dee06c701aeeca81a314a7d60216fa363005e27f4f0
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : Accessibility toolkit - ATK D-Bus Bridge
description: |
    The At-Spi2 Atk package contains a library that bridges ATK to At-Spi2 D-Bus service.
builddeps  :
    - pkgconfig32(atk)
    - pkgconfig32(atspi-2)
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(libxml-2.0)
    - libgcrypt-32bit-devel
emul32     : yes
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -rf $installdir/%libdir%/gnome-settings-daemon-3.0/
    fi
